AVRO-3673: improve task output
zcsizmadia/avro pull request #1
Opened 2023-02-15 14:13 UTC by Freds72AtWork

Minor fix to the merge request to support task chaining.
The AvroGenTask has an additional property: GeneratedFiles with full file spec of the generated files.

Example usage:
```xml
  <Target Name="AvroGenerate" BeforeTargets="BeforeCompile" >
    <Message Text="Generating C# classes from AVRO..." Importance="normal" />
	  <AvroBuildTask SchemaFiles="@(SchemaFiles)" OutDir="$(IntermediateOutputPath)avro">
		  <Output ItemName="GeneratedCodeFiles" TaskParameter="GeneratedFiles" />
	  </AvroBuildTask>
    <Message Text="Generated: %(GeneratedCodeFiles.Identity)" Importance="normal" />
```

Note: the fix also contains support for additional frameworks.

2023-02-16 14:06 UTC, zcsizmadia requested changes

2023-02-16 14:06 UTC, zcsizmadia commented on lang/csharp/README.md
> +	  </AvroBuildTask>
Is this correct?

2023-02-16 14:06 UTC, zcsizmadia commented on lang/csharp/src/apache/msbuild/Avro.msbuild.csproj
> +    <NoWarn>$(NoWarn);NU5104;NU5119</NoWarn>
What is this warning and why it is needed to be turned off?

2023-02-16 14:06 UTC, zcsizmadia commented on lang/csharp/src/apache/msbuild/AvroGenTask.cs
> +                        if (SkipDirectories)
The list of generated files should be coming from the codegen object. That code determines the location of the output files.

2023-02-16 14:11 UTC, Freds72AtWork commented on lang/csharp/README.md
> +	  </AvroBuildTask>
taken from my own code - was using a different name, fixing...

2023-02-16 14:12 UTC, zcsizmadia commented on lang/csharp/README.md
> +	  </AvroBuildTask>
Hmm... The whitespace is off, however I thought it should be </AvroGenTask> instead of </AvroBuildTask>>

2023-02-16 14:13 UTC, Freds72AtWork commented on lang/csharp/src/apache/msbuild/Avro.msbuild.csproj
> +    <NoWarn>$(NoWarn);NU5104;NU5119</NoWarn>
the build step generates a nupkg *before* the pack step (I don't understand why - this was there before I forked the project I guess?), hence making sure the 'nuget won't include nupkg in nupkg' warning doesn't break compilation

2023-02-16 14:14 UTC, Freds72AtWork commented on lang/csharp/src/apache/msbuild/Avro.msbuild.csproj
> +    <NoWarn>$(NoWarn);NU5104;NU5119</NoWarn>
the build step generates a nupkg *before* the pack step (I don't understand why - this was there before I forked the project I guess?), hence making sure the 'nuget won't include nupkg in nupkg' warning doesn't break compilation

2023-02-16 14:15 UTC, zcsizmadia commented on lang/csharp/src/apache/msbuild/Avro.msbuild.csproj
> +    <NoWarn>$(NoWarn);NU5104;NU5119</NoWarn>
I would investigate why this happens before turning off that warning

2023-02-16 14:17 UTC, zcsizmadia commented on lang/csharp/README.md
> +	  </AvroGenTask>
Fix the whitespace plz

2023-02-16 14:25 UTC, zcsizmadia commented on lang/csharp/README.md
> +	  </AvroGenTask>
![image](https://user-images.githubusercontent.com/8504099/219391553-d370d14e-8bc2-4ee4-96ee-bfdf9328ca82.png)

2023-02-16 14:28 UTC, Freds72AtWork commented on lang/csharp/src/apache/msbuild/Avro.msbuild.csproj
> +    <NoWarn>$(NoWarn);NU5104;NU5119</NoWarn>
looks like this was a side effect of the multi-target compilation, removed net6+7 fixed the warning (??)

2023-02-16 14:37 UTC, Freds72AtWork commented on lang/csharp/src/apache/msbuild/AvroGenTask.cs
> +                        if (SkipDirectories)
not familiar with that namespace, will investigate how to pull files from this object.

2023-02-16 14:41 UTC, zcsizmadia requested changes

2023-02-16 14:41 UTC, zcsizmadia commented on lang/csharp/common.props
> +    <DefaultLibraryTargetFrameworks>netstandard2.0;netstandard2.1;</DefaultLibraryTargetFrameworks>
Remove trailing `;`

2023-02-16 14:41 UTC, zcsizmadia commented on lang/csharp/src/apache/msbuild/Avro.msbuild.csproj
> +    <TargetFrameworks>netstandard2.0;netstandard2.1;</TargetFrameworks>
Remove `netstandard2.1`

2023-02-16 14:41 UTC, zcsizmadia commented on lang/csharp/src/apache/msbuild/Avro.msbuild.csproj
> +    <NoWarn>$(NoWarn);NU5104;</NoWarn>
Remove trailing `;`

2023-02-16 15:15 UTC, zcsizmadia requested changes

2023-02-16 15:15 UTC, zcsizmadia commented on lang/csharp/src/apache/test/MSBuild/AvroGenTaskTests.cs
> +                    Assert.That(generatedTaskItems.Any(item => item.ItemSpec == generatedFileInfo.FullName));
This should compare `expectedGeneratedFiles` and `generatedFileInfo` better. e.g. they should have the same number of items ...

2023-02-16 16:57 UTC, Freds72AtWork commented on lang/csharp/src/apache/msbuild/AvroGenTask.cs
> +                        if (SkipDirectories)
Not sure how to do without changing CodeGen interface - the CompileUnit object doesn't know about the files, the output is written to a stream:
```c#
                    // codegen.cs: 1190
                    string file = Path.Combine(dir, Path.ChangeExtension(CodeGenUtil.Instance.UnMangle(ctd.Name), "cs"));
                    using (var writer = new StreamWriter(file, false))
                    {
                        new_ns.Types.Add(ctd);
                        cscp.GenerateCodeFromNamespace(new_ns, writer, opts);
                        new_ns.Types.Remove(ctd);
                    }
```
would changing the WriteTypes method be an acceptable change?
```c#
...
/// <returns>List of filenames written</returns>
public virtual IList<string> WriteTypes(string outputdir, bool skipDirectories = false)
{
 ...
}
```

2023-02-16 17:27 UTC, zcsizmadia commented on lang/csharp/src/apache/msbuild/AvroGenTask.cs
> +                        if (SkipDirectories)
That function deinetely knwos about files, because it creates the output directory and creates all the files (using a stream writer). Personally I think we could add a `List<string> GeneratedFiles` property to `class CodeGen`, instead of adding arguments. `WriteTypes` clears `GeneratedFiles` prop inthe beginning and keeps adding the file names to it after the stream writer was successful.

In the msbuild task code, you just use `codegen.GeneratedFiles` to get the list.

2023-02-16 17:34 UTC, Freds72AtWork commented on lang/csharp/src/apache/msbuild/AvroGenTask.cs
> +                        if (SkipDirectories)
sorry if not clear - I expected the underlying CompileUnit to hold the files (it does not).
Not a big fan of mutating the CodeGen class, changing WriteFiles return type instead.

2023-02-16 17:41 UTC, zcsizmadia commented on lang/csharp/src/apache/msbuild/AvroGenTask.cs
> +                        if (SkipDirectories)
The reason I recommend the prop is that if the codegen object is passed around, the generated files is still available. Otherwise it is available only when the WriteTypes was called. Please use the prop if you dont mind

2023-02-17 07:50 UTC, Freds72AtWork commented on lang/csharp/src/apache/test/MSBuild/AvroGenTaskTests.cs
> +                    Assert.That(generatedTaskItems.Any(item => item.ItemSpec == generatedFileInfo.FullName));
done

2023-02-17 07:52 UTC, Freds72AtWork commented on lang/csharp/src/apache/msbuild/AvroGenTask.cs
> +                        if (SkipDirectories)
Done - minor variation anyway.

2023-02-17 08:09 UTC, zcsizmadia requested changes

2023-02-17 08:09 UTC, zcsizmadia commented on lang/csharp/src/apache/msbuild/AvroGenTask.cs
> +
Remove whitespace

2023-02-17 14:38 UTC, zcsizmadia approved these changes

2023-02-17 14:38 UTC, merged

2023-02-17 14:39 UTC, Freds72AtWork commented
thanks!

2023-02-17 14:40 UTC, zcsizmadia commented
https://github.com/apache/avro/pull/1966 is already building  the PR with your changes included.

2023-02-17 14:41 UTC, zcsizmadia commented
Fyi, I squashed the commits, so it looks like one commit. This is just minimizing the number of commits in avro:master. When  the PR will be merged into master, that will be squashed as well.